authapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),

    path('profile/', authapp.profile_view, name='profile'),
    path('profile/edit/', authapp.edit_profile, name='edit_profile'),
    path('profile/delete_picture/', authapp.delete_profile_picture, name='delete_profile_picture'),
    path('upload_profile_picture/', authapp.upload_profile_picture, name='upload_profile_picture'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py

from django.urls import path

import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('events/', mainapp.event_list, name='event_list'),
    path('events/<int:event_id>/', mainapp.event_detail, name='event_detail'),
    path('events/<int:event_id>/tasks/', mainapp.task_detail, name='task_detail'),
    path('events/create/', mainapp.create_event, name='create_event'),
    path('events/<int:event_id>/tasks/create/', mainapp.create_task, name='create_task'),

    path('update/<int:event_id>/', mainapp.update_event, name='update_event'),
    path('delete/<int:event_id>/', mainapp.delete_event, name='delete_event'),
    path('task/update_status/<int:task_id>/', mainapp.update_task_status, name='update_task_status'),
    path('task/edit/<int:task_id>/', mainapp.edit_task, name='edit_task'),
    path('task/delete/<int:task_id>/', mainapp.delete_task, name='delete_task'),
    path('invite/', mainapp.send_invitation, name='send_invitation'),
    path('invitations/confirm/<uuid:confirmation_link>/', mainapp.confirm_invitation, name='confirm_invitation'),
    path('invitations/', mainapp.invitation_list, name='invitation_list'),
    path('invitations/edit/<int:invitation_id>/', mainapp.edit_invitation, name='edit_invitation'),
    path('invitations/delete/<int:invitation_id>/', mainapp.delete_invitation, name='delete_invitation'),
    path('budget/', mainapp.budget_list, name='budget_list'),
    path('add_expense/<int:event_id>/', mainapp.add_expense, name='add_expense'),
    path('add_income/<int:event_id>/', mainapp.add_income, name='add_income'),
    path('add_budget/<int:event_id>/', mainapp.add_budget, name='add_budget'),
    path('edit_budget/<int:event_id>/', mainapp.edit_budget, name='edit_budget'),
    path('delete_data/<int:event_id>/', mainapp.delete_data, name='delete_data'),
    path('support/', mainapp.support_view, name='support'),
    path('all_answers', mainapp.all_faqs_view, name='all_answers'),
    path('review/', mainapp.write_review, name='write_review'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.sitemaps.views import sitemap

from mainapp.sitemaps import StaticViewSitemap, EventSitemap, BudgetSitemap, TaskSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'events': EventSitemap,
    'budget': BudgetSitemap,
    'tasks': TaskSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.db.models import Sum

from authapp.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    icon = models.ImageField(upload_to='category_icons/', blank=True, null=True, verbose_name="Изображение")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Event(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    description = models.TextField(verbose_name="Описание")
    location = models.CharField(max_length=200, verbose_name="Место проведения")
    deadline_date = models.DateField(verbose_name="Даты дедлайна")
    event_time = models.TimeField(verbose_name="Время проведения")
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_events', verbose_name="Создатель")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Категория")
    other_category = models.ImageField(upload_to='category_icons/', default='category_icons/default_image.png',
                                       blank=True, verbose_name="Нет категории")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")

    class Meta:
        verbose_name = "Мероприятие"
        verbose_name_plural = "Мероприятии"

    def __str__(self):
        return self.title


class Task(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=200, verbose_name="Название")
    description = models.TextField(blank=True, verbose_name="Описание")
    assignees = models.ManyToManyField(User, related_name='assigned_tasks', verbose_name="Исполнители")
    status = models.CharField(
        max_length=20,
        choices=[
            ('open', 'Открыта'),
            ('in_progress', 'В работе'),
            ('completed', 'Завершена'),
        ],
        default='open',
        verbose_name="Статус"
    )
    deadline = models.DateField(null=True, blank=True, verbose_name="Срок выполнения")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    completed = models.BooleanField(default=False, verbose_name="Завершена")

    class Meta:
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"
        ordering = ['deadline', '-created_at']

    def __str__(self):
        return self.title


class Invitation(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name="Мероприятие")
    email = models.EmailField(verbose_name="Email приглашённого")
    status = models.CharField(
        max_length=20,
        choices=[
            ('pending', 'Ожидает ответа'),
            ('accepted', 'Принято'),
            ('declined', 'Отклонено'),
        ],
        default='pending',
        verbose_name="Статус приглашения"
    )
    name = models.CharField(max_length=100, blank=True, verbose_name="Имя приглашённого")
    sent_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время отправки")
    confirmation_link = models.URLField(verbose_name="Уникальная ссылка для подтверждения", unique=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Отправитель")

    class Meta:
        verbose_name = "Приглашение"
        verbose_name_plural = "Приглашения"

    def __str__(self):
        return f"Приглашение для {self.name or self.email} на {self.event.title}"


class TransactionCategory(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название категории")

    class Meta:
        verbose_name = "Категория транзакции"
        verbose_name_plural = "Категории транзакций"

    def __str__(self):
        return self.name


class Expense(models.Model):
    category = models.ForeignKey(TransactionCategory, on_delete=models.SET_NULL, null=True, blank=True,
                                 verbose_name="Категория")
    other_category = models.CharField(max_length=100, null=True, blank=True, verbose_name="Другое")
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Сумма")
    date = models.DateField(verbose_name="Дата")
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='expenses', verbose_name="Мероприятие")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Участник мероприятия")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")

    class Meta:
        verbose_name = "Расход"
        verbose_name_plural = "Расходы"

    def __str__(self):
        return f"{self.amount} ({self.date})"


class Income(models.Model):
    category = models.ForeignKey(TransactionCategory, on_delete=models.SET_NULL, null=True, blank=True,
                                 verbose_name="Категория")
    other_category = models.CharField(max_length=100, null=True, blank=True, verbose_name="Другое")
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Сумма")
    date = models.DateField(verbose_name="Дата")
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='incomes', verbose_name="Мероприятие")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Участник мероприятия")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")

    class Meta:
        verbose_name = "Доход"
        verbose_name_plural = "Доходы"

    def __str__(self):
        return f"{self.amount} ({self.date})"


class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Участник мероприятия")
    event = models.OneToOneField(Event, on_delete=models.CASCADE, related_name='budget', verbose_name="Мероприятие")
    total_budget = models.DecimalField(max_digits=12, decimal_places=2, verbose_name="Общий бюджет")
    description = models.TextField(blank=True, null=True, verbose_name="Описание бюджета")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")

    class Meta:
        verbose_name = "Бюджет"
        verbose_name_plural = "Бюджеты"

    def __str__(self):
        return f"Бюджет для {self.event.title}"

    def expenses_total(self):
        return self.event.expenses.aggregate(Sum('amount'))['amount__sum'] or 0

    def incomes_total(self):
        return self.event.incomes.aggregate(Sum('amount'))['amount__sum'] or 0

    def remaining_budget(self):
        return self.total_budget - self.expenses_total()


class FAQ(models.Model):
    question = models.CharField(max_length=255, verbose_name="Вопрос")
    answer = models.TextField(verbose_name="Ответ")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")

    class Meta:
        verbose_name = "Вопрос-ответ (FAQ)"
        verbose_name_plural = "Вопросы-ответы (FAQ)"
        ordering = ['question']

    def __str__(self):
        return self.question


class SupportApplication(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,
                             verbose_name="Пользователь")
    email = models.EmailField(null=True, blank=True, verbose_name="Email")
    subject = models.CharField(max_length=200, verbose_name="Тема")
    message = models.TextField(verbose_name="Сообщение")
    STATUS_CHOICES = [
        ('open', 'Открыт'),
        ('in_progress', 'В обработке'),
        ('closed', 'Закрыт'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='open', verbose_name="Статус")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")

    class Meta:
        verbose_name = "Заявка в поддержку"
        verbose_name_plural = "Заявки в поддержку"
        ordering = ['-created_at']

    def __str__(self):
        return f"Ticket #{self.id} - {self.subject}"


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField(verbose_name='Текст отзыва')
    is_visible = models.BooleanField(default=False, verbose_name='Отображать на странице')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return f'Отзыв от {self.user.username}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

mainapp/templates/mainapp/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css.map' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/hammer.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favonicino.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favonicino.png' %}">
    {% block meta %}{% endblock %}
    {% block title %}
        <title>PlanIt!</title>
    {% endblock %}
</head>
<body>
<nav class="navbar bg-light sticky-top d-lg-none full-width-navbar">
    <div class="container">
        <div class="navbar-content">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                <img src="{% static 'logo.png' %}" alt="PlanIt!" height="100" width="180">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
             aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                        aria-label="Закрыть"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}"
                           aria-current="page" href="{% url 'mainapp:index' %}">Главная</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'event_list' %}active{% endif %}"
                               href="{% url 'mainapp:event_list' %}">Мероприятия</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'invitation_list' %}active{% endif %}"
                               href="{% url 'mainapp:invitation_list' %}">Список гостей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'budget_list' %}active{% endif %}"
                               href="{% url 'mainapp:budget_list' %}">Бюджет</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'support' %}active{% endif %}"
                               href="{% url 'mainapp:support' %}">Поддержка</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'profile' %}active{% endif %}"
                               href="{% url 'authapp:profile' %}">Профиль</a></li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти, {{ user.username }}</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'support' %}active{% endif %}"
                               href="{% url 'mainapp:support' %}">Поддержка</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'register' %}active{% endif %}"
                               href="{% url 'authapp:register' %}">Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}"
                               href="{% url 'authapp:login' %}">Войти</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</nav>
<nav class="navbar navbar-expand-lg navbar-light sticky-top d-none d-lg-block desktop-navbar-bg full-width-navbar">
    <div class="container">
        <div class="navbar-content">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                <img src="{% static 'logo.png' %}" alt="PlanIt!" height="110" width="200">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}"
                           aria-current="page" href="{% url 'mainapp:index' %}">Главная</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'event_list' %}active{% endif %}"
                               href="{% url 'mainapp:event_list' %}">Мероприятия</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'invitation_list' %}active{% endif %}"
                               href="{% url 'mainapp:invitation_list' %}">Список гостей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'budget_list' %}active{% endif %}"
                               href="{% url 'mainapp:budget_list' %}">Бюджет</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'support' %}active{% endif %}"
                               href="{% url 'mainapp:support' %}">Поддержка</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="

                                        {% if user.is_authenticated and user.get_profile_picture %}{{ user.get_profile_picture }}{% else %}{% static 'profile.png' %}{% endif %}"
                                     alt="Аватар пользователя" class="rounded-circle" width="30" height="30">
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item {% if request.resolver_match.url_name == 'profile' %}active{% endif %}"
                                       href="{% url 'authapp:profile' %}"><strong>Профиль</strong></a>
                                </li>
                                <li><a class="dropdown-item"
                                       href="{% url 'authapp:edit_profile' %}"><strong>Настройки</strong></a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item"
                                       href="{% url 'authapp:logout' %}"><strong>Выйти, {{ user.username }}</strong></a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'support' %}active{% endif %}"
                               href="{% url 'mainapp:support' %}">Поддержка</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'register' %}active{% endif %}"
                               href="{% url 'authapp:register' %}">Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}"
                               href="{% url 'authapp:login' %}">Войти</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="container">
    <div class="content-wrapper">
        {% block content %}
        {% endblock %}
    </div>
</div>
<footer class="footer mt-auto py-3">
    <div class="container">
        <div class="row text-muted">
            <div class="col-12 col-md-4 text-left">
                <h5>Следите за нами!</h5>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-muted underline-animation">vk.com/PlanIt!</a></li>
                    <li><a href="#" class="text-muted underline-animation">t.me/PlanIt! </a></li>
                    <li><a href="#" class="text-muted underline-animation">youtube.com/@PlanIt!</a></li>
                </ul>
            </div>
            <div class="col-12 col-md-4 text-left">
                <h5>Отзывы и Рекомендации</h5>
                <p>Читайте, что говорят наши пользователи:</p>
                <a href="{% url 'mainapp:write_review' %}" class="text-muted underline-animation">Оставить отзыв</a>
            </div>
            <div class="col-12 col-md-4 text-left">
                <h5>Контакты</h5>
                <p>Email: <a href="mailto:planit@mail.ru" class="text-muted underline-animation">planit@mail.ru</a></p>
                <p>Телефон: <a href="tel:+1234567890" class="text-muted underline-animation">+7(999)-999-99-99</a></p>
            </div>
        </div>
        <div class="row text-muted mt-3">
            <div class="col-12 text-center">
                <p class="fw-bold">© 2025 PlanIt! Все права защищены.</p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

mainapp/templates/mainapp/create_event.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block meta %}
    <meta name="description" content="{{ description }}">
    <meta name="keywords" content="{{ keywords }}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body d-flex flex-column align-items-center">
                <h1 class="card-title mb-4 text-center">Ваше мероприятие начинается здесь. <br> Давайте добавим его!
                </h1>
                <form method="post" enctype="multipart/form-data" class="w-100">
                    {% csrf_token %}
                    <div class="mb-4 mt-4">
                        <input type="text" name="title" id="id_title" class="form-control"
                               placeholder="Название мероприятия">
                    </div>

                    <div class="mb-4">
                        <textarea name="description" id="id_description" class="form-control" rows="4"
                                  placeholder="Описание"></textarea>
                    </div>

                    <div class="mb-4">
                        <input type="text" name="location" id="id_location" class="form-control"
                               placeholder="Место проведения">
                    </div>

                    <div class="mb-4">
                        <input type="date" name="deadline_date" id="id_deadline_date"
                               class="form-control form-control-lg">
                    </div>

                    <div class="mb-4">
                        <input type="time" name="event_time" id="id_event_time" class="form-control">
                    </div>

                    <div class="mb-4">
                        <label class="form-label">Выберите иконку для вашего мероприятия!</label>
                        <div class="d-flex flex-wrap justify-content-center">
                            {% for category in form.category.field.queryset %}
                                <div class="m-2 category-icon-container">
                                    <input type="radio" id="category_{{ category.id }}" name="category"
                                           value="{{ category.id }}" class="d-none">
                                    <label for="category_{{ category.id }}" class="category-icon-label">
                                        <img src="{{ category.icon.url }}" alt="{{ category.name }}"
                                             class="category-icon">
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="d-flex flex-column align-items-center">
                        <button type="submit" class="btn btn-secondary mb-2">Сохранить</button>
                        <a href="{% url 'mainapp:event_list' %}" class="underline-animation">К списку мероприятий</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <script>
        const categoryIconLabels = document.querySelectorAll('.category-icon-label');
        categoryIconLabels.forEach(label => {
            label.addEventListener('click', () => {
                const radioButton = label.previousElementSibling;
                radioButton.checked = true;
            });
        });
    </script>

{% endblock %}

mainapp/templates/mainapp/edit_task.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    <title>{{ title }}</title>
{% endblock %}
{% block meta %}
    <meta name="description" content="{{ description }}">
    <meta name="keywords" content="{{ keywords }}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body d-flex flex-column align-items-center">
                <h1 class="card-title mb-4 text-center">Редактирование задачи</h1>
                <form method="post" class="w-100">
                    {% csrf_token %}
                    <div class="mb-4 mt-4">
                        <input type="text" name="title" id="id_title" class="form-control"
                               placeholder="Название задачи" value="{{ form.initial.title }}">
                    </div>
                    <div class="mb-4">
                        <textarea name="description" id="id_description" class="form-control" rows="4"
                                  placeholder="Описание">{{ form.initial.description }}</textarea>
                    </div>
                    <div class="mb-4">
                        <input type="date" name="deadline" id="id_deadline"
                               class="form-control form-control-lg" value="{{ form.initial.deadline|date:'Y-m-d' }}">
                    </div>
                    <div class="mb-4">
                        <select name="status" id="id_status" class="form-control form-control-lg">
                            {% for value, label in form.fields.status.choices %}
                                <option value="{{ value }}"
                                        {% if value == form.initial.status %}selected{% endif %}>{{ label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-4">
                        <small class="form-text text-muted">{{ form.assignee_usernames.help_text }}</small>
                        <input type="text" name="assignee_usernames" id="id_assignee_usernames" class="form-control"
                               placeholder="Логины исполнителей (через запятую)"
                               value="{{ form.assignee_usernames.value }}">
                    </div>
                    <div class="d-flex flex-column align-items-center">
                        <button type="submit" class="btn btn-secondary mb-2">Сохранить</button>
                        <a href="{% url 'mainapp:task_detail' event.id %}" class="underline-animation">К списку задач</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}